---
# At least kernel 3.19 is needed in order to fix
# https://github.com/moby/moby/issues/21969
- include_tasks: kernel-{{ ansible_lsb.codename }}.yml
  failed_when: false

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_lsb.id | lower }}/gpg
    state: present
  tags:
    - packages

- name: Add HTTPS transport for apt
  apt:
    name: apt-transport-https
    state: installed
  tags:
    - packages

- name: Add Docker repository
  apt_repository:
    repo: >
      deb [arch=amd64] https://download.docker.com/linux/{{ ansible_lsb.id | lower }}
      {{ ansible_lsb.codename }}
      stable
    update_cache: yes
    state: present
  tags:
    - packages

- name: Install Docker
  apt:
    name: docker-ce=17.09.1~ce-0~debian
    state: present
  tags:
    - packages

- import_tasks: py2.yml
  when: >
    ansible_python_interpreter is undefined
    or ansible_python_interpreter != "/usr/bin/python3"

- import_tasks: py3.yml
  when: >
    ansible_python_interpreter is not undefined
    and ansible_python_interpreter == "/usr/bin/python3"

- name: Install Daemon configuration
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify:
    - restart docker
  tags:
    - configuration

- meta: flush_handlers

- name: Enable Docker
  service:
    name: docker
    enabled: yes
    state: started
  tags:
    - services
