all:
  children:
    vm1:
      hosts:
        vm.scummvm.org:2222:
      vars:
        # Make sure that the WORKER_HOST is set appropriately in
        # docker-compose.prod.yml for concurrency to work correctly. TODO: Fix
        # https://github.com/ansible/ansible/issues/22946 so this is not needed.
        workers:
          - amigaos
          - dreamcast
          - freemint
          - gcw0
          - haiku
          - maemo
          - nintendo
          - psp
          - ps3
          - raspberrypi
          - vita
    vm2:
      hosts:
        vm2.scummvm.org:7022:
      vars:
        workers:
          - android
          - debian-x86_64
          - debian-x86
          - ios
          - macos
          - windows
