all:
  children:
    vm1:
      hosts:
        vm.scummvm.org:2222:
      vars:
        ansible_python_interpreter: /usr/bin/python3
        sshd_port: 2222
        workers:
          - amigaos
          - dreamcast
          - freemint
          - gcw0
          - haiku
          - maemo
          - nintendo
          - psp
          - ps3
          - raspberrypi
          - vita
    vm2:
      hosts:
        vm2.scummvm.org:7022:
      vars:
        internal_buildbot_port: 8010
        sshd_port: 7022
        ssl_domains:
          - buildbot.scummvm.org
        workers:
          - android
          - debian-x86_64
          - debian-x86
          - ios
          - macos
          - windows
  vars:
    users:
      - name: criezy
        groups: sudo
        authorized:
          - https://github.com/criezy.keys
      - name: sev
        groups: sudo
        authorized:
          - https://github.com/sev-.keys
      - name: snover
        groups: sudo
        authorized:
          - https://github.com/csnover.keys
      - name: wjp
        groups: sudo
        authorized:
          - https://github.com/wjp.keys
