---
- hosts: all
  roles:
    - common
    - docker_host
    - buildbot_worker

- hosts: vm1
  roles:
    - buildbot_forwarder

- hosts: vm2
  roles:
    - ssl
    - ancient_web
    - buildbot_master
