all:
  children:
    vm1:
      hosts:
        localhost:2223:
      vars:
        workers:
          - amigaos
    vm2:
      hosts:
        localhost:2222:
      vars:
        workers:
          - debian-x86_64
