all:
  children:
    vm1:
      hosts:
        localhost:2223:
      vars:
        ansible_python_interpreter: /usr/bin/python3
        workers:
          - amigaos
    vm2:
      hosts:
        localhost:2222:
      vars:
        internal_buildbot_port: 8010
        workers:
          - debian-x86_64
  vars:
    users:
      - name: user
        groups: sudo
