---
- name: Retrieve Buildbot configuration
  git:
    repo: https://github.com/csnover/scummvm-docker.git
    dest: /srv/buildbot
  tags:
    - configuration

- name: Run Buildbot workers
  docker_service:
    project_src: /srv/buildbot
    files:
      - docker-compose.yml
      - docker-compose.prod.yml
    services:
      "{{ workers | map('regex_replace', '^', 'buildbot-') | list }}"
    state: present

# TODO: Stop any old workers
