---
- name: restart buildmaster
  docker_service:
    project_src: /srv/buildbot
    files:
      - docker-compose.yml
      - docker-compose.master-prod.yml
    services:
      - web
      - buildbot
    state: present
    restarted: true
