---
- name: Set the time zone
  timezone:
    name: UTC
  notify:
    - restart cron
  tags:
    - configuration
    - time

- name: Uninstall ntpd
  apt:
    name: ntp
    state: absent
  tags:
    - packages
    - time

- name: Enable timesyncd
  service:
    name: systemd-timesyncd
    enabled: yes
    state: started
  tags:
    - services
    - time

- name: Install MOTD
  template:
    src: motd.j2
    dest: /etc/motd
  tags:
    - configuration
    - motd

- import_tasks: firewall.yml
- import_tasks: ssh.yml
- import_tasks: users.yml
