---
- name: Set the time zone
  timezone:
    name: UTC
  notify:
    - restart cron
  tags:
    - configuration

- name: Install MOTD
  template:
    src: motd.j2
    dest: /etc/motd
  tags:
    - configuration

- import_tasks: ssh.yml
- import_tasks: users.yml
