---
- name: Set the time zone
  timezone:
    name: UTC
  notify:
    - restart cron
  tags:
    - configuration

- name: Disable ntpd
  service:
    name: ntpd
    enabled: no
    state: stopped
  tags:
    - services

- name: Enable timesyncd
  service:
    name: systemd-timesyncd
    enabled: yes
    state: started
  tags:
    - services

- name: Install MOTD
  template:
    src: motd.j2
    dest: /etc/motd
  tags:
    - configuration

- import_tasks: firewall.yml
- import_tasks: ssh.yml
- import_tasks: users.yml
