---
- name: Retrieve Buildbot configuration
  git:
    repo: https://github.com/csnover/scummvm-docker.git
    dest: /srv/buildbot
  notify:
    - restart buildmaster
  tags:
    - configuration

- name: Retrieve Buildbot secrets configuration
  copy:
    src: secrets.cfg
    dest: /srv/buildbot/secrets.cfg
  notify:
    - restart buildmaster
  tags:
    - configuration

- name: Install Buildbot buildmaster settings
  template:
    src: docker-compose.master-prod.yml.j2
    dest: /srv/buildbot/docker-compose.master-prod.yml
  notify:
    - restart buildmaster
  tags:
    - configuration

- name: Run Buildbot buildmaster
  docker_service:
    project_src: /srv/buildbot
    files:
      - docker-compose.yml
      - docker-compose.master-prod.yml
    services:
      - web
      - buildbot
    state: present
  tags:
    - services
