---
- name: Install Apache 2
  apt:
    name: apache2
    state: latest
  tags:
    - ancient_web
    - apache2
    - packages

- name: Start Apache 2
  service:
    name: apache2
    enabled: yes
    state: started
  tags:
    - ancient_web
    - apache2
    - services

- name: Activate Apache modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - deflate
    - headers
    - proxy
    - proxy_http
    - proxy_wstunnel
    - ssl
  notify:
    - reload apache2
  tags:
    - ancient_web
    - apache2
    - configuration

- import_tasks: ssl.yml

- name: Install Buildbot Apache configuration
  template:
    src: buildbot.scummvm.org.conf.j2
    dest: /etc/apache2/sites-enabled/buildbot.scummvm.org.conf
  notify:
    - reload apache2
  tags:
    - ancient_web
    - apache2
    - configuration
