---
- name: Install Apache 2
  apt:
    name: apache2
    state: latest
  tags:
    - ancient_web
    - apache2
    - packages

- name: Start Apache 2
  service:
    name: apache2
    enabled: yes
    state: started
  tags:
    - ancient_web
    - apache2
    - services

- name: Activate Apache modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - alias
    - deflate
    - headers
    - proxy
    - proxy_http
    - proxy_wstunnel
    - ssl
  notify:
    - reload apache2
  tags:
    - ancient_web
    - apache2
    - configuration

- name: Install Apache SSL include
  copy:
    src: scummvm-ssl.conf
    dest: /etc/apache2/scummvm-ssl.conf
  tags:
    - ancient_web
    - apache2
    - configuration
    - ssl

- include_tasks: config.yml
  with_items:
    - buildbot.scummvm.org
