- name: Install pyOpenSSL for CSR generation
  pip:
    executable: >-
      {{ "pip3" if
           ansible_python_interpreter is not undefined
           and ansible_python_interpreter == "/usr/bin/python3"
         else "pip" }}
    name: pyOpenSSL
    state: latest
  tags:
    - ancient_web
    - packages
    - ssl

- name: Create directory for SSL certificates
  file:
    path: /etc/letsencrypt/live/scummvm.org
    state: directory
  tags:
    - ancient_web
    - configuration
    - ssl

- name: Generate SSL private key
  openssl_privatekey:
    path: /etc/letsencrypt/live/scummvm.org/privkey.pem
    state: present
  tags:
    - ancient_web
    - configuration
    - ssl

- name: Generate SSL CSR
  openssl_csr:
    path: /etc/ssl/private/scummvm.org.csr
    privatekey_path: /etc/letsencrypt/live/scummvm.org/privkey.pem
    subject_alt_name: "DNS:{{ ssl_domains | join(',DNS:') }}"
    state: present
  tags:
    - ancient_web
    - configuration
    - ssl

- name: Generate self-signed SSL certificate
  openssl_certificate:
    csr_path: /etc/ssl/private/scummvm.org.csr
    path: /etc/letsencrypt/live/scummvm.org/fullchain.pem
    privatekey_path: /etc/letsencrypt/live/scummvm.org/privkey.pem
    provider: selfsigned
    state: present
  when: ssl_selfsigned is not undefined and ssl_selfsigned
  tags:
    - ancient_web
    - configuration
    - ssl
